name: Publish Python Package

on:
  push:
   branches:
     - main

jobs:
  build-and-test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Set up Python 3.10
         uses: actions/setup-python@v5
         with:
           python-version: "3.10"
       - name: Install dependencies
         run: pip install -e .[dev]
       - name: Test with pytest
         run: pytest
  publish:
     needs: build-and-test
     runs-on: ubuntu-latest
     permissions:
       id-token: write
     steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: python-package
        - name: Upload package to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}